train:
  batch_size: 32
  num_epochs: 10
  learning_rate: 0.001
model:
  model_name: resnet50
  pretrained: true
  num_classes: 2
paths:
  train_data: "data\\train"
  val_data: "data\\val"
  model_save_path: "models\\resnet50_mycl.pth"